### ISSUE TITLE
Rust wrapping for hdfs::binding::hdfsGetPathInfo()

### ISSUE THREAD

**Issue by dorny** [hyunsik/hdfs-rs#1]
Hi,

could you please add Rust wrapping for `hdfs::binding::hdfsGetPathInfo()`?
If i understand it correctly, it's the only way to get actual block size for specific file.
Other functions are returning only defualt block size (global or for some path).
Thanks.

**Comment by hyunsik** [comment]
Sure, I'll add it within few days. Thank you for reporting.

**Comment by dorny** [comment]
Thanks.
Now I've realized I will also need `hdfs::binding::hdfsListDirectory`. It returns dyn array of same struct as `hdfsGetPathInfo`. Could you add it too?

**Comment by hyunsik** [comment]
@dorny No problem :)

**Comment by hyunsik** [comment]
I'm sorry for delay. I was on vacation. I will commit it soon.

**Comment by hyunsik** [comment]
@dorny I just added the API. Please check out the commit change. I'll also add `hdfsListDirectory` too tomorrow. Thanks!
